version: '3.8'

services:
  database-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: database-ii-project
    ports:
      - "8501:8501"  # Puerto de Streamlit
    volumes:
      # Montar datasets para poder actualizarlos sin reconstruir la imagen
      - ./data/datasets:/app/data/datasets
      # Montar resultados de experimentos
      - ./experiments/results:/app/experiments/results
      # Opcional: montar el código para desarrollo (descomenta para hot-reload)
      # - ./gui:/app/gui
      # - ./indexes:/app/indexes
      # - ./sql_parser:/app/sql_parser
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      # Configuración adicional de Streamlit
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=200
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Recursos opcionales (descomenta si necesitas limitar)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 2G
    #     reservations:
    #       cpus: '1'
    #       memory: 512M

networks:
  default:
    name: database-ii-network
